#version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: inventario_db_prod
    hostname: db_host
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_vol:/var/lib/postgresql/data
    networks:
      - LAB_TYMA
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: inventario_ti_api:latest
    container_name: inventario_api_prod
    hostname: api_host
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - LAB_TYMA

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: inventario_ti_frontend:latest
    container_name: inventario_frontend_prod
    hostname: frontend_host
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://api_host:8000
    depends_on:
      - backend
    networks:
      - LAB_TYMA

volumes:
  postgres_data_vol:
    name: inventario_postgres_data

networks:
  LAB_TYMA:
    external: true