global:
  scrape_interval: 15s

scrape_configs:
  # Auto-monitoreo de Prometheus
  - job_name: 'Prometheus'
    static_configs:
      - targets: [
                  'localhost:9090',
                  'localhost:9115',
                  ]  # Blackbox Exporter]
#------------------
  # Monitoreo por ICMP (Ping)
  - job_name: 'Blackbox ICMP'
    metrics_path: /probe
    params:
      module: [icmp_check] # <--- Debe coincidir con el nombre definido en blackbox.yml
    static_configs:
      - targets:
          - localhost
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9115
#------------------
  # - job_name: 'Proyecto DevOps'
  #   static_configs:
  #     - targets: [
  #                 'inventario_api_prod:8000',
  #                 ]  # Reemplaza con la dirección de tu aplicación
#----------------
  # Probes HTTP con Blackbox
  - job_name: 'Proyecto DevOps'
    metrics_path: /metrics
    static_configs:
      - targets: [
            'inventario_api_prod:8000',
            'postgres-exporter:9187',
            'inventario_frontend_prod:9101',
        ] 

  # Monitoreo por ICMP (Ping)
  - job_name: 'Blackbox ICMP - Proyecto DevOps'
    metrics_path: /probe
    params:
      module: [icmp_check] # <--- Debe coincidir con el nombre definido en blackbox.yml
    static_configs:
      - targets: [
            '172.200.0.5',
          ] 
          
    # relabel_configs:
    #   - source_labels: [__address__]
    #     target_label: __param_target
    #   - source_labels: [__param_target]
    #     target_label: instance
    #   - target_label: __address__
    #     replacement: localhost:9115


# # Job para el exporter de PostgreSQL
#   - job_name: 'Proyecto DevOps - db PostgreSQL'
#     metrics_path: '/metrics'
#     static_configs:
#       - targets: [
#           'postgres-exporter:9187',
#         ]

#   - job_name: 'Proyecto DevOps - Frontend'
#     metrics_path: /metrics
#     static_configs:
#       - targets: [
#               'inventario_frontend_prod:8501',
#               ] 
