name: Docker Build Check

on:
  push:
    branches: [ "**" ] # Se ejecuta en cualquier rama
  pull_request:
    branches: [ "main" ]

jobs:
  build-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Validar Build del Backend
        uses: docker/build-push-action@v5
        with:
          context: ./001-Inventario-MVP/backend
          file: ./001-Inventario-MVP/backend/Dockerfile
          push: false

      - name: Validar Build del Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./001-Inventario-MVP/frontend
          file: ./001-Inventario-MVP/frontend/Dockerfile
          push: false
      
      - name: Validar Build de Observabilidad
        uses: docker/build-push-action@v5
        with:
          context: ./002_Observabilidad   
          file: ./002_Observabilidad/Dockerfile
          push: false